# Generated by Django 2.1 on 2019-06-26 17:21

import django.contrib.postgres.fields
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=1000)),
                ('isbn', models.CharField(max_length=26)),
                ('authors', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=1000), size=None)),
                ('number_of_pages', models.PositiveIntegerField()),
                ('publisher', models.CharField(max_length=1000)),
                ('country', models.CharField(max_length=500)),
                ('release_date', models.DateField()),
            ],
        ),
    ]
